[options]
logfile = /var/log/knockd.log

[opencloseALL]
sequence      = 7:udp,8:udp,9:udp
seq_timeout   = 15
tcpflags      = syn
start_command = /usr/sbin/iptables -I INPUT -s %IP% -j ACCEPT
cmd_timeout   = 3600
stop_command  = /usr/sbin/iptables -D INPUT -s %IP% -j ACCEPT